server:
  port: 8090
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/szptcircle?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  type-aliases-package: com.zhang.szptcircle.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml